#' @title bulma Modal
#'
#' @author David Granjon, \email{dgranjon@@ymail.com}
#'
#' @description Create a modal for bulma \url{https://bulma.io/documentation/components/modal/}.
#'
#' @param ... Any element.
#' 
#' @export
#'
#' @examples
bulmaModal <- function(...) {
  modalTag <- shiny::tags$div(
    class = "modal",
    shiny::tags$div(
      class = "modal-background",
      shiny::tags$div(
        class = "modal-content",
        style = "top: 50%;",
        bulmaBox(...)
      ),
      shiny::tags$button(
       class = "modal-close",
       `aria-label` = "close"
      )
    )
  )
  
  # click outside of the modal will close it
  modal <- shiny::tagList(
    shiny::singleton(
      shiny::tags$head(
        shiny::includeScript(
          system.file(file.path("js", "bulma-modal-js.js"), package = "shinybulma")
        )
      )
    ),
    modalTag
  )
  
  modal
  
}


#' @title show a bulma modal
#'
#' @author David Granjon, \email{dgranjon@@ymail.com}
#'
#' @description Show a modal. Use it only on the server side \url{https://bulma.io/documentation/components/menu/}.
#'
#' @param modal Modal generated by bulmaModal.
#' 
#' @export
#'
#' @examples
showBulmaModal <- function(modal) {
  # shinyjs::addClass(
  #   id = modal$attribs$id, 
  #   class = "is-active"
  # )
  
  modal[[2]]$attribs$class <- "modal is-active"
  modal
  
}